
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://uhmgreyhats.github.io/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id

google-tracking-id: "UA-86663423-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Grey Hats UHM"
title: "Grey Hats UHM"
description: "Official Grey Hats at UHM club website."
keywords: "grey, hats, uhm, uh manoa, manoa, university of hawaii at manoa, grey hats, cybersecurity, cyber, hacker"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/logo.ico"

background-img: "../img/home.jpeg"

##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Viva la France!"
  - text: "Fuck it, Ship it"
  - text: "Works on my machine"
  - text: "If it works 99% of the time, it's 100% wrong, but 200% good enough"
  - text: "Fish meme is best meme"

# me-img: "/img/logo.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/uhmgreyhats.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/logo-36p.png"
icon-48p: "/img/web-app/logo-48p.png"
icon-72p: "/img/web-app/logo-72p.png"
icon-96p: "/img/web-app/logo-96p.png"
icon-144p: "/img/web-app/logo-144p.png"
icon-192p: "/img/web-app/logo-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

# events:
#   - image: "/img/timeline/spidertocat.png"
#     date: "September 2013 - Today"
#     description: "Saving the neighborhood!"
#   - image: "/img/timeline/baracktocat.jpg"
#     date: "September 2007 - August 2013"
#     description: "Started coding"
#
# # First image of the Timeline
#
# timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "greyhats@hawaii.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: ""
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/uhmgreyhats"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username:
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Announcements: 'latest-post'
  # Timeline: 'timeline'
  Calendar: 'calendar'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji

theme: jekyll-theme-hacker